"""
utils/report_generator.py — Professional PDF Report Generation
"""

import os
import re
import uuid
from datetime import datetime

from reportlab.platypus import (
    SimpleDocTemplate, Paragraph, Spacer,
    ListFlowable, ListItem, Table, TableStyle,
    KeepTogether,
)
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib import colors
from reportlab.lib.enums import TA_CENTER, TA_LEFT
from reportlab.pdfgen import canvas as pdf_canvas

# ---------------------------------------------------------------------------
# Colors
# ---------------------------------------------------------------------------
NAVY    = colors.HexColor("#1B2A4A")
BLUE    = colors.HexColor("#2E5090")
ACCENT  = colors.HexColor("#4A7CC7")
CARD_BG = colors.HexColor("#EEF2F8")
META_BG = colors.HexColor("#243860")
DIVIDER = colors.HexColor("#CBD5E8")
WHITE   = colors.white
TXT     = colors.HexColor("#1A1A1A")
GRAY    = colors.HexColor("#555555")
LIGHT   = colors.HexColor("#888888")

# ---------------------------------------------------------------------------
# Page geometry
# ---------------------------------------------------------------------------
PAGE_W, PAGE_H = A4
MARGIN   = 0.75 * inch
BOT_MAR  = 1.0  * inch
USABLE_W = PAGE_W - 2 * MARGIN   # ≈ 487 pts
HALF_W   = USABLE_W / 2


# ---------------------------------------------------------------------------
# Exception
# ---------------------------------------------------------------------------
class ReportGenerationError(Exception):
    pass


# ---------------------------------------------------------------------------
# Numbered Canvas  — Page X of Y footer on every page
# ---------------------------------------------------------------------------
class _NumberedCanvas(pdf_canvas.Canvas):
    def __init__(self, *args, **kwargs):
        pdf_canvas.Canvas.__init__(self, *args, **kwargs)
        self._pages: list[dict] = []

    def showPage(self):
        self._pages.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        total = len(self._pages)
        for i, state in enumerate(self._pages, 1):
            self.__dict__.update(state)
            self._stamp(i, total)
            pdf_canvas.Canvas.showPage(self)
        pdf_canvas.Canvas.save(self)

    def _stamp(self, page_num: int, total: int) -> None:
        self.saveState()
        self.setStrokeColor(DIVIDER)
        self.setLineWidth(0.5)
        self.line(MARGIN, 52, PAGE_W - MARGIN, 52)
        self.setFont("Helvetica", 8)
        self.setFillColor(LIGHT)
        self.drawCentredString(
            PAGE_W / 2, 36,
            f"Generated by AI Resume Analyzer   |   Page {page_num} of {total}"
        )
        self.restoreState()


# ---------------------------------------------------------------------------
# Styles
# ---------------------------------------------------------------------------
def _build_styles() -> dict:
    return {
        "doc_title": ParagraphStyle("DocTitle",
            fontName="Helvetica-Bold", fontSize=22, leading=26,
            textColor=WHITE, alignment=TA_CENTER, spaceAfter=5),

        "doc_sub": ParagraphStyle("DocSub",
            fontName="Helvetica", fontSize=10, leading=14,
            textColor=colors.HexColor("#B0C4DE"), alignment=TA_CENTER),

        "meta_lbl": ParagraphStyle("MetaLbl",
            fontName="Helvetica-Bold", fontSize=8, leading=10,
            textColor=colors.HexColor("#8AAAD0"),
            alignment=TA_CENTER, spaceAfter=4),

        "meta_val": ParagraphStyle("MetaVal",
            fontName="Helvetica", fontSize=10, leading=13,
            textColor=WHITE, alignment=TA_CENTER),

        # Score number — explicit leading prevents line overlap
        "card_num": ParagraphStyle("CardNum",
            fontName="Helvetica-Bold", fontSize=30, leading=34,
            textColor=NAVY, alignment=TA_CENTER),

        "card_unit": ParagraphStyle("CardUnit",
            fontName="Helvetica", fontSize=9, leading=12,
            textColor=BLUE, alignment=TA_CENTER),

        "card_lbl": ParagraphStyle("CardLbl",
            fontName="Helvetica-Bold", fontSize=8, leading=11,
            textColor=GRAY, alignment=TA_CENTER),

        "sec_head": ParagraphStyle("SecHead",
            fontName="Helvetica-Bold", fontSize=11, leading=14,
            textColor=WHITE, alignment=TA_LEFT),

        "body": ParagraphStyle("Body",
            fontName="Helvetica", fontSize=10,
            textColor=TXT, alignment=TA_LEFT,
            leading=16, spaceAfter=4),

        "bullet": ParagraphStyle("BulletTxt",
            fontName="Helvetica", fontSize=10,
            textColor=TXT, alignment=TA_LEFT, leading=15),
    }


STYLES: dict = _build_styles()


# ---------------------------------------------------------------------------
# Public API  (function names / return types preserved)
# ---------------------------------------------------------------------------

def generate_report_filename(original_filename: str = "") -> str:
    if original_filename:
        stem, _ = os.path.splitext(os.path.basename(original_filename))
        # Replace non-alphanumeric chars, then collapse multiple underscores
        safe = re.sub(r"[^\w\-]", "_", stem)
        safe = re.sub(r"_+", "_", safe).strip("_")
        if safe:
            return f"{safe}_Report.pdf"
    return f"report_{uuid.uuid4().hex[:8]}.pdf"


def create_pdf_report(
    result: dict,
    output_folder: str,
    original_filename: str = "",
) -> str:
    if not os.path.isdir(output_folder):
        raise ReportGenerationError(
            f"Report folder missing: '{output_folder}'."
        )
    if not isinstance(result, dict) or not result:
        raise ReportGenerationError("Result must be a non-empty dict.")

    filename  = generate_report_filename(original_filename)
    save_path = os.path.join(output_folder, filename)

    try:
        _render_pdf(result, save_path, original_filename)
    except Exception as exc:
        raise ReportGenerationError(f"Render failed: {exc}") from exc

    return filename


def safe_list(value) -> list:
    if isinstance(value, list):
        return value
    if isinstance(value, str) and value.strip():
        return [value]
    return []


def create_heading(text: str) -> Table:
    """Backward-compatible shim."""
    return _section_bar(text)


def create_bullet_list(items: list) -> ListFlowable:
    """Backward-compatible shim."""
    return _bullets(items)


# ---------------------------------------------------------------------------
# Private: header block
# ---------------------------------------------------------------------------

def _header_block(original_filename: str) -> Table:
    """Navy title banner + two-column meta row (Resume | Generated)."""
    date_str = datetime.now().strftime("%B %d, %Y")
    name = ""
    if original_filename:
        stem, _ = os.path.splitext(os.path.basename(original_filename))
        name = re.sub(r"_+", " ", stem).strip()

    # Title area
    title_cell = [
        Spacer(1, 0.28 * inch),
        Paragraph("AI Resume Analysis Report", STYLES["doc_title"]),
        Spacer(1, 0.04 * inch),
        Paragraph("Generated by AI Resume Analyzer", STYLES["doc_sub"]),
        Spacer(1, 0.22 * inch),
    ]
    title_tbl = Table([[title_cell]], colWidths=[USABLE_W])
    title_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), NAVY),
        ("TOPPADDING",    (0,0),(-1,-1), 0),
        ("BOTTOMPADDING", (0,0),(-1,-1), 0),
        ("LEFTPADDING",   (0,0),(-1,-1), 0),
        ("RIGHTPADDING",  (0,0),(-1,-1), 0),
    ]))

    # Meta row — TWO columns only (no developer column)
    def _mcell(lbl: str, val: str) -> Table:
        """Each meta cell is its own nested Table to avoid any overlap."""
        inner = Table(
            [[Paragraph(lbl, STYLES["meta_lbl"])],
             [Paragraph(val or "—", STYLES["meta_val"])]],
            colWidths=[HALF_W],
        )
        inner.setStyle(TableStyle([
            ("ALIGN",         (0,0),(-1,-1), "CENTER"),
            ("TOPPADDING",    (0,0),(-1,-1), 5),
            ("BOTTOMPADDING", (0,0),(-1,-1), 5),
            ("LEFTPADDING",   (0,0),(-1,-1), 4),
            ("RIGHTPADDING",  (0,0),(-1,-1), 4),
        ]))
        return inner

    meta_tbl = Table(
        [[_mcell("RESUME", name or "Uploaded Resume"),
          _mcell("GENERATED", date_str)]],
        colWidths=[HALF_W, HALF_W],
    )
    meta_tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), META_BG),
        ("LINEAFTER",     (0,0),(0,-1),  0.5, colors.HexColor("#3A5080")),
        ("TOPPADDING",    (0,0),(-1,-1), 0),
        ("BOTTOMPADDING", (0,0),(-1,-1), 0),
        ("LEFTPADDING",   (0,0),(-1,-1), 0),
        ("RIGHTPADDING",  (0,0),(-1,-1), 0),
    ]))

    outer = Table([[title_tbl], [meta_tbl]], colWidths=[USABLE_W])
    outer.setStyle(TableStyle([
        ("TOPPADDING",    (0,0),(-1,-1), 0),
        ("BOTTOMPADDING", (0,0),(-1,-1), 0),
        ("LEFTPADDING",   (0,0),(-1,-1), 0),
        ("RIGHTPADDING",  (0,0),(-1,-1), 0),
    ]))
    return outer


# ---------------------------------------------------------------------------
# Private: score cards  — NESTED TABLE approach (zero overlap possible)
# ---------------------------------------------------------------------------

def _score_cards(resume_score: int, ats_score: int) -> Table:
    """
    Flat 3-row × 2-column Table.
    Row 0 → large score numbers
    Row 1 → unit text  ("out of 100" / "ATS Compatibility")
    Row 2 → category labels ("RESUME SCORE" / "ATS SCORE")

    Every cell contains exactly ONE Paragraph.
    Explicit rowHeights pin each row's height so nothing can ever overlap,
    regardless of font rendering differences across platforms.
    """
    tbl = Table(
        [
            # Row 0: large numbers
            [Paragraph(str(resume_score), STYLES["card_num"]),
             Paragraph(f"{ats_score}%",   STYLES["card_num"])],
            # Row 1: unit text
            [Paragraph("out of 100",        STYLES["card_unit"]),
             Paragraph("ATS Compatibility", STYLES["card_unit"])],
            # Row 2: category labels
            [Paragraph("RESUME SCORE", STYLES["card_lbl"]),
             Paragraph("ATS SCORE",    STYLES["card_lbl"])],
        ],
        colWidths=[HALF_W, HALF_W],
        # Pin each row height explicitly — no automatic collapse possible.
        # Row 0: 30pt font needs ~36pt line height + 16pt top/bottom breathing room = 52pt
        # Row 1: 9pt font ~11pt line height + padding = 22pt
        # Row 2: 8pt font ~10pt line height + 14pt bottom breathing room = 30pt
        rowHeights=[56, 22, 32],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), CARD_BG),
        ("BOX",           (0,0),(-1,-1), 1.5, NAVY),
        ("LINEAFTER",     (0,0),(0,-1),  0.75, DIVIDER),
        # Center text horizontally in every cell
        ("ALIGN",         (0,0),(-1,-1), "CENTER"),
        # Middle-align within each fixed-height row
        ("VALIGN",        (0,0),(-1,-1), "MIDDLE"),
        # Uniform horizontal padding only — vertical handled by rowHeights
        ("LEFTPADDING",   (0,0),(-1,-1), 8),
        ("RIGHTPADDING",  (0,0),(-1,-1), 8),
        ("TOPPADDING",    (0,0),(-1,-1), 0),
        ("BOTTOMPADDING", (0,0),(-1,-1), 0),
        # Extra top space before the first row (score number)
        ("TOPPADDING",    (0,0),(-1,0),  14),
        # Extra bottom space after the last row (label)
        ("BOTTOMPADDING", (0,2),(-1,2),  14),
    ]))
    return tbl




# ---------------------------------------------------------------------------
# Private: sections
# ---------------------------------------------------------------------------

def _section_bar(text: str) -> Table:
    tbl = Table(
        [[Paragraph(text.upper(), STYLES["sec_head"])]],
        colWidths=[USABLE_W],
    )
    tbl.setStyle(TableStyle([
        ("BACKGROUND",    (0,0),(-1,-1), NAVY),
        ("TOPPADDING",    (0,0),(-1,-1), 7),
        ("BOTTOMPADDING", (0,0),(-1,-1), 7),
        ("LEFTPADDING",   (0,0),(-1,-1), 12),
        ("RIGHTPADDING",  (0,0),(-1,-1), 12),
    ]))
    return tbl


def _bullets(items: list) -> ListFlowable:
    display = items if items else ["None detected."]
    return ListFlowable(
        [
            ListItem(
                Paragraph(str(item), STYLES["bullet"]),
                bulletColor=ACCENT,
                leftIndent=16,
                spaceAfter=3,
            )
            for item in display
        ],
        bulletType="bullet",
        bulletFontSize=8,
        leftIndent=20,
        spaceAfter=6,
    )


def _bullet_section(heading: str, items: list) -> KeepTogether:
    return KeepTogether([
        _section_bar(heading),
        Spacer(1, 0.1 * inch),
        _bullets(safe_list(items)),
        Spacer(1, 0.15 * inch),
    ])


def _summary_section(text: str) -> KeepTogether:
    return KeepTogether([
        _section_bar("AI Professional Summary"),
        Spacer(1, 0.1 * inch),
        Paragraph(text or "No summary available.", STYLES["body"]),
        Spacer(1, 0.15 * inch),
    ])


# ---------------------------------------------------------------------------
# Main renderer
# ---------------------------------------------------------------------------

def _render_pdf(result: dict, save_path: str, original_filename: str = "") -> None:
    doc = SimpleDocTemplate(
        save_path,
        pagesize=A4,
        leftMargin=MARGIN,
        rightMargin=MARGIN,
        topMargin=MARGIN,
        bottomMargin=BOT_MAR,
        title="AI Resume Analysis Report",
        author="AI Resume Analyzer",
    )

    story: list = []

    story.append(_header_block(original_filename))
    story.append(Spacer(1, 0.3 * inch))

    story.append(_score_cards(
        int(result.get("resume_score", 0)),
        int(result.get("ats_score",    0)),
    ))
    story.append(Spacer(1, 0.3 * inch))

    for heading, key in [
        ("Technical Skills", "technical_skills"),
        ("Soft Skills",      "soft_skills"),
        ("Strengths",        "strengths"),
        ("Missing Skills",   "missing_skills"),
        ("Suggestions",      "suggestions"),
        ("Weaknesses",       "weaknesses"),
    ]:
        story.append(_bullet_section(heading, result.get(key, [])))

    story.append(_summary_section(result.get("summary", "")))

    doc.build(story, canvasmaker=_NumberedCanvas)
